apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "capi-hetzner-cluster.name" . }}
spec:
  clusterNetwork:
    pods:
      {{- with .Values.network.clusterNetwork.podCidrBlocks }}
      cidrBlocks:
      {{- toYaml . | nindent 8 }}
      {{- end }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: {{ include "capi-hetzner-cluster.name" . }}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: HetznerCluster
    name: {{ include "capi-hetzner-cluster.name" . }}
