{{- range .Values.workers }}
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    nodepool: {{ include "capi-hetzner-cluster.name" $ }}-{{ .name }}
  annotations:
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-min-size: "{{ .minNodes }}"
    cluster.x-k8s.io/cluster-api-autoscaler-node-group-max-size: "{{ .maxNodes }}"
    capacity.cluster-autoscaler.kubernetes.io/cpu: "{{ .flavor.cpu }}"
    capacity.cluster-autoscaler.kubernetes.io/memory: "{{ .flavor.memory }}"
    capacity.cluster-autoscaler.kubernetes.io/ephemeral-disk: "{{ .flavor.ephemeralStorage }}"
    capacity.cluster-autoscaler.kubernetes.io/maxPods: "{{ .flavor.maxPods }}"
  name: {{ include "capi-hetzner-cluster.name" $ }}-{{ .name }}
spec:
  clusterName: {{ include "capi-hetzner-cluster.name" $ }}
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        nodepool: {{ include "capi-hetzner-cluster.name" $ }}-{{ .name }}
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: {{ include "capi-hetzner-cluster.name" $ }}-{{ .name }}
      clusterName: {{ include "capi-hetzner-cluster.name" $ }}
      failureDomain: {{ .region }}
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: HCloudMachineTemplate
        name: {{ include "capi-hetzner-cluster.name" $ }}-{{ .name }}
      version: {{ $.Values.kubernetes.version }}
{{- end }}
